name: Windows CI
on:
  workflow_dispatch:
  workflow_call:

env:
  HAXE_VERSION: 4.3.7

jobs:
  windows:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: ${{ env.HAXE_VERSION }}
      - name: Set HAXEPATH
        run: echo "HAXEPATH=$HAXE_STD_PATH/.." >> $GITHUB_ENV
      - name: Install Haxe dependencies
        run: |
          haxelib git hxcpp https://github.com/th2l-devs/hxcpp --quiet
          haxelib install format --quiet
          haxelib install hxp
      - name: Enable HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=~/.hxcpp" >> $GITHUB_ENV
      - name: Configure Lime
        run: haxelib dev lime ${{ github.workspace }}
      - name: Rebuild Lime
        run: |
          haxelib run lime rebuild windows -32 -release -nocolor -nocffi
          haxelib run lime rebuild windows -64 -release -nocolor -nocffi
          haxelib run lime rebuild windows -arm64 -release -nocolor -nocffi -D HXCPP_ARM64
      - name: Upload Artifact (x86)
        uses: actions/upload-artifact@v4
        with:
          name: Windows-NDLL
          path: |
            ndll/Windows/
            !**/.gitignore
            lime.png
          if-no-files-found: error
      - name: Upload Artifact (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: Windows64-NDLL
          path: |
            ndll/Windows64/
            !**/.gitignore
            lime.png
          if-no-files-found: error
      - name: Upload Artifact (ARM64)
        uses: actions/upload-artifact@v4
        with:
          name: WindowsArm64-NDLL
          path: |
            ndll/WindowsArm64/
            !**/.gitignore
            lime.png
          if-no-files-found: error
